### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by Zhankevich** [Toolz-at/gtm-conset-mode#20]
When reviewing your template, we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This option is required to be set for any asynchronous consent management script load to delay tag execution.

**Comment by joandysson** [comment]
@Zhankevich #24 Done!
