### ISSUE TITLE
setDefaultConsentState should run on every page load

### ISSUE THREAD

**Issue by Zhankevich** [Toolz-at/gtm-conset-mode#21]
When reviewing your template, we've noticed that setDefaultConsentState is called only if no `consentMode` record in localStorage, that potentially can mean that setDefaultConsentState may run only once within single browser. That is why we are asking you to revisit this to make sure that setDefaultConsentState runs on every page load.

**Comment by joandysson** [comment]
@Zhankevich  #24 Done
